TOP = ../..
include $(TOP)/mk/boilerplate.mk

SRC_RUNTEST_OPTS += +RTS -K1m -RTS

include $(TOP)/mk/target.mk

FAST_OPTS = runtime_files/houses.plate
NORM_OPTS = runtime_files/rad.plate
SLOW_OPTS = runtime_files/four.plate
