TOP = ../..
include $(TOP)/mk/boilerplate.mk

FAST_OPTS = -nt 8 -dt 4 -nv 10 -dv 6 -de 6
NORM_OPTS = -nt 40 -dt 5 -nv 60 -dv 6 -de 6
SLOW_OPTS = -nt 80 -dt 8 -nv 100 -dv 8 -de 8

#PROG_ARGS =

include $(TOP)/mk/target.mk

