
clean:
	$(RM) -fr ./*/*/*.hi
	$(RM) -fr ./*/*/*.o
	$(RM) -fr ./*/*/*.stdout
	$(RM) -fr ./*/*/Main
	$(RM) real/fulsom/Bah           # Remove these separately
	$(RM) spectral/exact-reals/Era  # Remove these separately
	$(RM) real/compress/Lzw         # Remove these separately
	$(RM) real/maillist/runtime_files/fast.tex # God know what this is

