TOP = ../..
include $(TOP)/mk/boilerplate.mk
include $(TOP)/mk/target.mk

FAST_OPTS = 3500
NORM_OPTS = 11000
SLOW_OPTS = 22000
# Official shootout setting, takes about 1s in 2018
# SLOW_OPTS = 10000

# The benchmark game also uses -fllvm, which we can't since it might
# not be available on the developer's machine.
