resolver: lts-16.19
extra-deps:
  - binaryen-0.0.5.0
  - url: https://github.com/tweag/inline-js/archive/26c89ec30039445d6b3735cb58fda91b38400375.tar.gz
    subdirs:
      - inline-js-core
flags:
  binaryen:
    system-binaryen: true
  ghc-asterius:
    integer-gmp: true
packages:
  - asterius
  - ghc-toolkit
  - lib/ghc-asterius
  - lib/ghci-asterius
  - wasm-toolkit
