resolver: lts-15.10
extra-deps:
  - binaryen-0.0.1.1
  - url: https://github.com/tweag/inline-js/archive/114848a9f750b5e9c2f8ca056cc29d84bbab0bae.tar.gz
    subdirs:
      - inline-js-core
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-tinfo6.200426.tar.xz
        content-length: 150942924
        sha256: 55f956aa35e0a121ad9936e7a800045854e24dae0b19f12a558d1da29020ef1e
    linux64-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius.200426.tar.xz
        content-length: 148248316
        sha256: d9c2e0bf333d24121cd193fc7f0b806002ad2e1e80d797a6455ee00ec9ecc75e
    linux64-custom-asterius-musl:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-musl.200426.tar.xz
        content-length: 165435056
        sha256: 619c89c6f78f5c378acad48900587770e1249bcbe06334f6d2efec4383536ec4
    macosx-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-macosx-custom-asterius.200426.tar.xz
        content-length: 159018316
        sha256: 327369a6226da78f62c4a49f99b95060a66d0bbed4ddfc168992bf1fd09f607b
