resolver: lts-14.21
extra-deps:
  - https://github.com/tweag/binaryen/archive/6791ac17d020cab228f4d01e7acb05fcbc84cbf8.tar.gz
  - url: https://github.com/tweag/inline-js/archive/bd000373e0f02d213a881119298e1aea5962e149.tar.gz
    subdirs:
      - inline-js-core
  - https://github.com/tweag/wabt/archive/cedd1578d98806cc2fb5922a2e70e8fb0f016d63.tar.gz
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.6.5:
        url: https://8664-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        content-length: 147961428
        sha256: 293f6d208168746e0a9d69a08e482d2115f06bd8bb870e1bd186c0a6b104c78f
    linux64-custom-asterius:
      8.6.5:
        url: https://8665-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        content-length: 147160424
        sha256: 0ba75ff51219b856b1960f30dc080952c05f61d48e47c468dddcae741c4dc270
    linux64-custom-asterius-musl:
      8.6.5:
        url: https://8667-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-alpine-linux.tar.xz
        content-length: 154901428
        sha256: e5f8eb43e5c0a3469394a1cc62dd73f3d14d5faf8849f0f5fc5bbd88b876604c
    macosx-custom-asterius:
      8.6.5:
        url: https://8663-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        content-length: 139345980
        sha256: d187ab6dcaae81e88fcbb398dcb68aee950fb73b386c951ceceef9b1885f87a7
