resolver: lts-15.13
extra-deps:
  - binaryen-0.0.1.1
  - url: https://github.com/tweag/inline-js/archive/114848a9f750b5e9c2f8ca056cc29d84bbab0bae.tar.gz
    subdirs:
      - inline-js-core
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-tinfo6.200513.tar.xz
        content-length: 151380256
        sha256: c7e77e53f71bff9eef84212e07fff569ce69ce280db0423047e044134768d8d8
    linux64-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius.200513.tar.xz
        content-length: 148504768
        sha256: 8c19275812abafcc9cff75da48c8958aef6ae5aa4e24568618f17ca51f4d2094
    linux64-custom-asterius-musl:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-musl.200513.tar.xz
        content-length: 165675408
        sha256: 0ca37a9ab3b09c890825d3e1dc28c4f7744af8c49fc0fbbb8b5d2eb87dfef018
    macosx-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-macosx-custom-asterius.200513.tar.xz
        content-length: 159079000
        sha256: 1ef26e9d83555a1457dc9260b4473fedde0eac4ada7306530bfb3bf071ba4337
