TOP = ../..
include $(TOP)/mk/boilerplate.mk
include $(TOP)/mk/target.mk

FAST_OPTS = runtime_files/fast
NORM_OPTS = runtime_files/norm
SLOW_OPTS = runtime_files/slow

CLEAN_FILES += runtime_files/*.tex
