TOP = ../..
include $(TOP)/mk/boilerplate.mk
-include opts.mk
include $(TOP)/mk/target.mk

# The first parameter controls iteration count, the second number of particles.
# For stable results, increment the first parameter, for more realistic benchmark
# load the second.
FAST_OPTS =  200  18 
NORM_OPTS =  500  80
SLOW_OPTS = 1000 300
