name: ghc-toolkit
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - genapply/**/**
  - CHANGELOG.md
  - LICENSE
  - README.md

data-files:
  - boot-libs/**/**
  - ghc-libdir/**/**

include-dirs:
  - ghc-libdir/include
  - include-private

c-sources:
  - cbits/ghc_constants.c

cc-options: -Wall -Wextra -O3 -fPIC -std=c11 -DASTERIUS
cpp-options: -DASTERIUS

custom-setup:
  dependencies:
    - base
    - Cabal
    - containers
    - directory
    - filepath
    - process

ghc-options: -Wall

dependencies:
  - base
  - Cabal
  - containers
  - directory
  - filepath
  - ghc
  - process

library:
  source-dirs: src
  other-extensions:
    - DuplicateRecordFields
    - FlexibleInstances
    - GADTs
    - LambdaCase
    - NamedFieldPuns
    - RecordWildCards
    - StandaloneDeriving
    - StrictData
    - UndecidableInstances
