TOP = ../..
include $(TOP)/mk/boilerplate.mk

# Override default SRCS; the default is all source files, but
# we don't want to include paraffins.c
SRCS=Main.hs

include $(TOP)/mk/target.mk


FAST_OPTS = 11
NORM_OPTS = 14
SLOW_OPTS = 15
