TOP = ../..
include $(TOP)/mk/boilerplate.mk
include $(TOP)/mk/target.mk


# Every increment takes about 10 times as much time as the last. In 2018, 9
# took 1.5s. The benchmark is stable enough that that's also OK for slow mode.
FAST_OPTS = 8
NORM_OPTS = 9
SLOW_OPTS = 9
