name: asterius
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - test/array/**/*.hs
  - test/fib/**/*.hs
  - test/jsffi/**/*.hs
  - test/jsffi/jsffi.mjs
  - test/rtsapi/**/*.hs
  - test/rtsapi/rtsapi.mjs
  - test/stableptr/**/*.hs
  - test/todomvc/**/*.hs
  - test/todomvc/**/*.html
  - test/teletype/**/*.hs
  - test/bytearray/**/*.hs
  - test/bytearraymini/**/*.hs
  - test/bigint/**/*.hs
  - test/cloudflare/**/*.hs
  - test/cloudflare/cloudflare.mjs
  - test/cloudflare-new/*.hs
  - test/cloudflare-new/Worker.mjs
  - test/cloudflare-new/*.json
  - test/nomain/**/*.hs
  - test/ghc-testsuite/**/*.hs
  - test/ghc-testsuite/**/*.stdout
  - test/exception/**/*.hs
  - test/regression60/**/*.hs
  - test/sizeof_md5context/**/*.hs
  - test/largenum/**/*.hs
  - test/nodeio/**/*.hs
  - test/time/**/*.hs
  - test/primitive/**/*.hs
  - test/argv/**/*.hs
  - test/endianness/**/*.hs

ghc-options: -Wall

_exe-ghc-options: &exe-ghc-options
  - -threaded -rtsopts "-with-rtsopts=-H512m -I0 -qg"

dependencies:
  - base
  - binary
  - bytestring
  - Cabal
  - containers
  - deepseq
  - directory
  - filepath
  - ghc-asterius
  - ghc-boot-asterius
  - ghc-prim
  - ghc-toolkit
  - ghci-asterius
  - inline-js-core
  - mtl
  - process
  - transformers

internal-libraries:
  asterius-types:
    source-dirs: src-types
    dependencies:
      - template-haskell

library:
  source-dirs: src
  dependencies:
    - asterius-types
    - binaryen
    - template-haskell-asterius

executables:
  ahc:
    source-dirs: ghc-bin-asterius
    c-sources:
      - ghc-bin-asterius/hschooks.c
    main: Main.hs
    ghc-options: -no-hs-main -threaded -rtsopts "-with-rtsopts=-H512m -I0 -qg"
    dependencies:
      - asterius

  Setup-ghc-prim:
    source-dirs: app
    main: Setup-ghc-prim.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  ahc-link:
    source-dirs: app
    main: ahc-link.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  ahc-ld:
    source-dirs: app
    main: ahc-ld.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  ahc-dist:
    source-dirs: app
    main: ahc-dist.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  ahc-cabal:
    source-dirs: app
    main: ahc-cabal.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  unlit:
    source-dirs: app
    main: unlit.c

  genconstants:
    source-dirs: app
    main: genconstants.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

tests:
  fib:
    source-dirs: test
    main: fib.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  jsffi:
    source-dirs: test
    main: jsffi.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  array:
    source-dirs: test
    main: array.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  stableptr:
    source-dirs: test
    main: stableptr.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  rtsapi:
    source-dirs: test
    main: rtsapi.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  todomvc:
    source-dirs: test
    main: todomvc.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  teletype:
    source-dirs: test
    main: teletype.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  bytearray:
    source-dirs: test
    main: bytearray.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  bytearraymini:
    source-dirs: test
    main: bytearraymini.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  bigint:
    source-dirs: test
    main: bigint.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  cloudflare:
    source-dirs: test
    main: cloudflare.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  cloudflare-new:
    source-dirs: test
    main: cloudflare-new.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  nomain:
    source-dirs: test
    main: nomain.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  exception:
    source-dirs: test
    main: exception.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  ghc-testsuite:
    source-dirs: test
    main: ghc-testsuite.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius
      - tasty
      - tasty-hunit
      - cassava
      - optparse-applicative

  ghc-testsuite-with-ghc:
    source-dirs: test
    main: ghc-testsuite-with-ghc.hs
    ghc-options: *exe-ghc-options
    dependencies: []

  sizeof_md5context:
    source-dirs: test
    main: sizeof_md5context.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  regression60:
    source-dirs: test
    main: regression60.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  largenum:
    source-dirs: test
    main: largenum.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  th:
    source-dirs: test
    main: th.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  nodeio:
    source-dirs: test
    main: nodeio.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  text:
    source-dirs: test
    main: text.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  parsec:
    source-dirs: test
    main: parsec.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  rts:
    source-dirs: test
    main: rts.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  time:
    source-dirs: test
    main: time.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  primitive:
    source-dirs: test
    main: primitive.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  argv:
    source-dirs: test
    main: argv.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius

  endianness:
    source-dirs: test
    main: endianness.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - asterius
