name: asterius
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - test/fib/fib.hs
  - test/jsffi/jsffi.hs
  - test/array/array.hs
  - test/th/Splices.hs
  - test/th/th.hs

data-files:
  - rts/rts.js
  - boot.sh

custom-setup:
  dependencies:
    - base
    - Cabal
    - ghc-toolkit

ghc-options: -Wall

dependencies:
  - attoparsec
  - base
  - binary
  - binaryen
  - bytestring
  - Cabal
  - cereal
  - containers
  - deepseq
  - directory
  - dlist
  - filepath
  - ghc
  - ghc-prim
  - ghc-toolkit
  - hashable
  - mtl
  - optparse-applicative
  - pretty-show
  - primitive
  - process
  - unordered-containers
  - vector

library:
  source-dirs: src
  other-modules: Paths_asterius
  other-extensions:
    - DeriveGeneric
    - DeriveDataTypeable
    - FlexibleContexts
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MagicHash
    - NamedFieldPuns
    - OverloadedLists
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - TypeFamilies
    - UnboxedTuples

executables:
  ahc:
    source-dirs: app
    main: ahc.hs
    ghc-options: -threaded -feager-blackholing -with-rtsopts=-N
    dependencies:
      - asterius

  ahc-boot:
    source-dirs: app
    main: ahc-boot.hs
    ghc-options: -threaded -feager-blackholing -with-rtsopts=-N
    dependencies:
      - asterius

  ahc-link:
    source-dirs: app
    main: ahc-link.hs
    ghc-options: -threaded -feager-blackholing -with-rtsopts=-N
    dependencies:
      - asterius

tests:
  nir-test:
    source-dirs: test
    main: nir-test.hs
    dependencies:
      - asterius
    other-extensions:
      - OverloadedLists
      - OverloadedStrings

  fib:
    source-dirs: test
    main: fib.hs
    dependencies:
      - asterius

  jsffi:
    source-dirs: test
    main: jsffi.hs
    dependencies:
      - asterius

  array:
    source-dirs: test
    main: array.hs
    dependencies:
      - asterius

  th:
    source-dirs: test
    main: th.hs
    dependencies:
      - asterius
