name: bazel

on:
  - push
  - pull_request

env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:

  shell:
    name: bazel-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Mount Bazel cache
        uses: actions/cache@v2
        with:
          path: ~/repo-cache
          key: repo-cache-nixpkgs-${{ env.cache-version }}

      - name: setup-nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          install_url: https://releases.nixos.org/nix/nix-2.3.16/install

      - name: setup-cachix
        uses: cachix/cachix-action@v10
        with:
          name: asterius
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: cachix-watch-store
        if: ${{ github.repository_owner == 'tweag' }}
        run: |
          cachix watch-store -c9 -j2 asterius &

      - name: Bazel build
        run: |
          nix-shell bazel/nix/bazel_build_shell.nix --pure --run '
            set -euo pipefail
            bazel build //asterius:binaries --config=ci
          '
